### ISSUE TITLE
帮忙看看这个chromedriver报错

### ISSUE THREAD

**Issue by LoserForever88** [Mattoids/nas-tools#2]
## 你使用的 NAStool 是什么版本，什么环境？

> NAStool 版本: vx.x.x
>v3.2.6-1
> 环境: docker or windows or Synology
>Windows 11, 64 bit

## 你遇到什么问题了？

即使把所有配置都删了重新来过，启动nastool的时候会报下面这个错，之前旧官方版本的nastool没有这问题

`Traceback (most recent call last):
  File "run.py", line 143, in <module>
  File "app\helper\chrome_helper.py", line 252, in init_chrome
  File "app\helper\chrome_helper.py", line 44, in init_driver
  File "webdriver_manager\chrome.py", line 39, in install
  File "webdriver_manager\core\manager.py", line 30, in _get_driver_path
  File "webdriver_manager\core\download_manager.py", line 28, in download_file
  File "webdriver_manager\core\http.py", line 33, in get
  File "webdriver_manager\core\http.py", line 16, in validate_response
ValueError: There is no such driver by url https://chromedriver.storage.googleapis.com/117.0.5938/chromedriver_win32.zip
`

## 是否已经浏览过Issues、Wiki及TG公众号仍无法解决？
是
> 请搜索Issues列表、查看wiki跟TG公众号的更新说明，已经解释过的问题不要重复提问

## 你期望的结果

> 描述以下你期望的结果
只求能正常启动nastool

## 给出程序界面截图、后台运行日志或配置文件

> ![image](https://github.com/Mattoids/nas-tools/assets/122156717/c6da71e5-2487-4f6e-b4b3-b97bf98f5935)

> 如UI BUG请提供截图及配置文件截图
> 其它问题提供后台日志，如为Docker请提供docker的日志

**Comment by Mattoids** [comment]
你安装一个 chrome 浏览器试试，看报错内容介绍，应该是chrome内核无法获取到，导致项目无法运行。

**Comment by LoserForever88** [comment]
> 你安装一个 chrome 浏览器试试，看报错内容介绍，应该是chrome内核无法获取到，导致项目无法运行。

有，很早已经安装了，还是报错
那报错里的chrome版本号就是我现在chrome的版本，我更新了chrome，那报错的版本号也跟着变

**Comment by LoserForever88** [comment]
我发现不只我一个人有这错误，在nastool群里搜“chrome”的话有人也曾经有这报错，有人怀疑是因为chrome自动更新了导致这个报错，作者可以用最新版本的chrome调试一下吗？应该很容易就能重现的。

我试了要用这个版本才没有问题：https://github.com/developer-wlj/nas-tools-backup/releases/tag/v3.2.3.2

**Comment by Mattoids** [comment]
该问题已在 v3.2.7 版本中修复，请升级最新版本解决当前问题

**Comment by LoserForever88** [comment]
> 该问题已在 v3.2.7 版本中修复，请升级最新版本解决当前问题

是的，没问题了，这帖可以关了。
